# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sage/Apps/Linux_Unreal_Engine_5.6.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	P_GAS-Android-DebugGame  \
	P_GAS-Android-Development  \
	P_GAS-Android-Shipping  \
	P_GAS-Linux-DebugGame  \
	P_GAS-Linux-Development  \
	P_GAS-Linux-Shipping  \
	P_GAS-LinuxArm64-DebugGame  \
	P_GAS-LinuxArm64-Development  \
	P_GAS-LinuxArm64-Shipping  \
	P_GAS \
	P_GASEditor-Linux-DebugGame  \
	P_GASEditor-Linux-Development  \
	P_GASEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend P_GASEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug P_GASEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

P_GAS-Android-DebugGame:
	 $(BUILD) P_GAS Android DebugGame  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-Android-Development:
	 $(BUILD) P_GAS Android Development  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-Android-Shipping:
	 $(BUILD) P_GAS Android Shipping  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-Linux-DebugGame:
	 $(BUILD) P_GAS Linux DebugGame  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-Linux-Development:
	 $(BUILD) P_GAS Linux Development  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-Linux-Shipping:
	 $(BUILD) P_GAS Linux Shipping  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-LinuxArm64-DebugGame:
	 $(BUILD) P_GAS LinuxArm64 DebugGame  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-LinuxArm64-Development:
	 $(BUILD) P_GAS LinuxArm64 Development  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS-LinuxArm64-Shipping:
	 $(BUILD) P_GAS LinuxArm64 Shipping  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GAS: P_GAS-Linux-Development

P_GASEditor-Linux-DebugGame:
	 $(BUILD) P_GASEditor Linux DebugGame  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GASEditor-Linux-Development:
	 $(BUILD) P_GASEditor Linux Development  -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" $(ARGS)

P_GASEditor: P_GASEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/sage/Documents/Unreal Projects/P_GAS/P_GAS.uproject" -Game 

.PHONY: $(TARGETS)
